// This file is autogenerated by lib/css-plugin.js
export const snackbar: string;
export const snackbarShow: string;
export const snackbarHide: string;
export const text: string;
export const button: string;
export const focusRing: string;