// This file is autogenerated by lib/css-plugin.js
export const spinnerCircle: string;
export const spinnerGapPatch: string;
export const spinnerCircleClipper: string;
export const spinnerLeft: string;
export const spinnerLeftSpin: string;
export const spinnerRight: string;
export const spinnerRightSpin: string;
export const spinnerFadeout: string;
export const spinnerFadeOut: string;
export const spinnerContainer: string;
export const spinnerContainerRotate: string;
export const spinnerLayer: string;
export const spinnerFillUnfillRotate: string;